Compare Stations
==========

To get Q stations, I need to make sure that they are available. The table I have of the stations doesn't seem to list it...

In [1]:
import pandas as pd

station_info = 'Remote-Booth-Station.csv'
test_turnstile = 'modern/turnstile_170527.txt'

In [2]:
station_df = (pd.read_csv(station_info, header=0)
              .drop('Division', axis=1))
turnstile_df = (pd.read_csv(test_turnstile, header=0)
                .drop('DIVISION', axis=1))

In [3]:
station_df.head()

  Remote  Booth       Station Line Name
0   R001   A060  WHITEHALL ST        R1
1   R001   A058  WHITEHALL ST        R1
2   R001  R101S   SOUTH FERRY        R1
3   R002   A077     FULTON ST  ACJZ2345
4   R002   A081     FULTON ST  ACJZ2345

In [4]:
turnstile_df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,00:00:00,REGULAR,6184841,2095161
1,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,04:00:00,REGULAR,6184865,2095167
2,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,08:00:00,REGULAR,6184891,2095192
3,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,12:00:00,REGULAR,6184973,2095275
4,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,16:00:00,REGULAR,6185217,2095326

In [5]:
turnstile_df[turnstile_df['LINENAME'].str.contains('Q')]

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,00:00:00,REGULAR,6184841,2095161
1,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,04:00:00,REGULAR,6184865,2095167
2,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,08:00:00,REGULAR,6184891,2095192
3,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,12:00:00,REGULAR,6184973,2095275
4,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,16:00:00,REGULAR,6185217,2095326
5,A002,R051,02-00-00,59 ST,NQR456W,05/20/2017,20:00:00,REGULAR,6185506,2095379
6,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,00:00:00,REGULAR,6185634,2095402
7,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,04:00:00,REGULAR,6185655,2095410
8,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,08:00:00,REGULAR,6185665,2095420
9,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,12:00:00,REGULAR,6185734,2095480
10,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,16:00:00,REGULAR,6185889,2095539
11,A002,R051,02-00-00,59 ST,NQR456W,05/21/2017,20:00:00,REGULAR,6186111,2095577
12,A002,R051,02-00-00,59 ST,NQR456W,05/22/2017,00:00:00,REGULAR,6186215,2095600
13,A002,R051,02-00-00,59 ST,NQR456W,05/22/2017,08:00:00,REGULAR,6186282,2095704
14,A002,R051,02-00-00,59 ST,NQR456W,05/22/2017,12:00:00,REGULAR,6186432,2095955
15,A002,R051,02-00-00,59 ST,NQR456W,05/22/2017,16:00:00,REGULAR,6186689,2096029
16,A002,R051,02-00-00,59 ST,NQR456W,05/22/2017,20:00:00,REGULAR,6187464,2096100
17,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,00:00:00,REGULAR,6187676,2096118
18,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,04:00:00,REGULAR,6187697,2096120
19,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,08:00:00,REGULAR,6187746,2096237
20,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,12:00:00,REGULAR,6187922,2096521
21,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,16:00:00,REGULAR,6188310,2096603
22,A002,R051,02-00-00,59 ST,NQR456W,05/23/2017,20:00:00,REGULAR,6189254,2096664
23,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,00:00:00,REGULAR,6189483,2096697
24,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,04:00:00,REGULAR,6189502,2096698
25,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,08:00:00,REGULAR,6189551,2096815
26,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,12:00:00,REGULAR,6189812,2097116
27,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,16:00:00,REGULAR,6190313,2097189
28,A002,R051,02-00-00,59 ST,NQR456W,05/24/2017,20:00:00,REGULAR,6191210,2097246
29,A002,R051,02-00-00,59 ST,NQR456W,05/25/2017,00:00:00,REGULAR,6191488,2097275
...,...,...,...,...,...,...,...,...,...,...
187518,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,00:00:00,REGULAR,117440512,71
187519,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,04:00:00,REGULAR,117440512,71
187520,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,08:00:00,REGULAR,117440512,71
187521,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,12:00:00,REGULAR,117440512,71
187522,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,16:00:00,REGULAR,117440512,71
187523,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/22/2017,20:00:00,REGULAR,117440512,71
187524,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,00:00:00,REGULAR,117440512,71
187525,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,04:00:00,REGULAR,117440512,71
187526,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,08:00:00,REGULAR,117440512,71
187527,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,12:00:00,REGULAR,117440512,71
187528,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,16:00:00,REGULAR,117440512,71
187529,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/23/2017,20:00:00,REGULAR,117440512,71
187530,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,00:00:00,REGULAR,117440512,71
187531,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,04:00:00,REGULAR,117440512,71
187532,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,08:00:00,REGULAR,117440512,71
187533,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,12:00:00,REGULAR,117440512,71
187534,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,16:00:00,REGULAR,117440512,71
187535,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/24/2017,20:00:00,REGULAR,117440512,71
187536,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,00:00:00,REGULAR,117440512,71
187537,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,04:00:00,REGULAR,117440512,71
187538,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,08:00:00,REGULAR,117440512,71
187539,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,12:00:00,REGULAR,117440512,71
187540,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,16:00:00,REGULAR,117440512,71
187541,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/25/2017,20:00:00,REGULAR,117440512,71
187542,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,00:00:00,REGULAR,117440512,71
187543,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,04:00:00,REGULAR,117440512,71
187544,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,08:00:00,REGULAR,117440512,71
187545,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,12:00:00,REGULAR,117440512,71
187546,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,16:00:00,REGULAR,117440512,71
187547,R612,R057,01-05-01,ATL AV-BARCLAY,BDNQR2345,05/26/2017,20:00:00,REGULAR,117440512,71

In [6]:
turnstile_df[turnstile_df['LINENAME'].str.contains('Q')]['LINENAME'].unique()

array(['NQR456W', 'NQRW', 'ACENQRS1237W', 'BDFMNQRW', 'LNQR456W',
       'JNQRZ6W', 'BQ', 'BQS', 'Q', 'BDNQR', 'BDNQR2345', 'DFNQ', 'FQ',
       'BDFQ6', '1237ACENQRSW', '1237ACENQRS', '456LNQRW', '456NQRW',
       '7NQW', 'NQW', '2345BDNQR'], dtype=object)

In [7]:
second_ave = turnstile_df[(turnstile_df['LINENAME'] == 'Q') &
                          (turnstile_df['STATION'].str.contains('2 AVE'))]
second_ave.STATION.unique()

array(['72 ST-2 AVE', '86 ST-2 AVE', '96 ST-2 AVE'], dtype=object)

In [8]:
lex_ave_456 = turnstile_df[(turnstile_df['LINENAME'].str.contains('6')) &
                           (turnstile_df['STATION'].str.contains('ST'))]
lex_ave_456.STATION.unique()

array(['59 ST', '14 ST-UNION SQ', 'CANAL ST', 'CHAMBERS ST', 'SPRING ST',
       'BLEECKER ST', 'ASTOR PL', '23 ST', '28 ST', '33 ST',
       'GRD CNTRL-42 ST', '51 ST', '68ST-HUNTER CO', '77 ST', '86 ST',
       '96 ST', '103 ST', '110 ST', '116 ST', '125 ST', '3 AV 138 ST',
       "E 143/ST MARY'S", 'E 149 ST', 'ST LAWRENCE AV', 'PARKCHESTER',
       'CASTLE HILL AV', 'WESTCHESTER SQ'], dtype=object)

In [17]:
turnstile_df[(turnstile_df.STATION == '86 ST') &
             (turnstile_df.LINENAME.str.contains('4') |
              turnstile_df.LINENAME.str.contains('5') |
              turnstile_df.LINENAME.str.contains('6'))]

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME,DESC,ENTRIES,EXITS
155395,R249,R179,01-00-00,86 ST,456,05/20/2017,00:00:00,REGULAR,2117999,33101495
155396,R249,R179,01-00-00,86 ST,456,05/20/2017,04:00:00,REGULAR,2118035,33101612
155397,R249,R179,01-00-00,86 ST,456,05/20/2017,08:00:00,REGULAR,2118056,33101771
155398,R249,R179,01-00-00,86 ST,456,05/20/2017,12:00:00,REGULAR,2118102,33102607
155399,R249,R179,01-00-00,86 ST,456,05/20/2017,16:00:00,REGULAR,2118230,33103674
155400,R249,R179,01-00-00,86 ST,456,05/20/2017,20:00:00,REGULAR,2118409,33104701
155401,R249,R179,01-00-00,86 ST,456,05/21/2017,00:00:00,REGULAR,2118555,33105191
155402,R249,R179,01-00-00,86 ST,456,05/21/2017,04:00:00,REGULAR,2118589,33105343
155403,R249,R179,01-00-00,86 ST,456,05/21/2017,08:00:00,REGULAR,2118599,33105450
155404,R249,R179,01-00-00,86 ST,456,05/21/2017,12:00:00,REGULAR,2118621,33106009
155405,R249,R179,01-00-00,86 ST,456,05/21/2017,16:00:00,REGULAR,2118715,33107023
155406,R249,R179,01-00-00,86 ST,456,05/21/2017,20:00:00,REGULAR,2118854,33107798
155407,R249,R179,01-00-00,86 ST,456,05/22/2017,00:00:00,REGULAR,2118961,33108115
155408,R249,R179,01-00-00,86 ST,456,05/22/2017,04:00:00,REGULAR,2118983,33108150
155409,R249,R179,01-00-00,86 ST,456,05/22/2017,08:00:00,REGULAR,2119042,33108907
155410,R249,R179,01-00-00,86 ST,456,05/22/2017,12:00:00,REGULAR,2119091,33111075
155411,R249,R179,01-00-00,86 ST,456,05/22/2017,16:00:00,REGULAR,2119261,33112782
155412,R249,R179,01-00-00,86 ST,456,05/22/2017,20:00:00,REGULAR,2119593,33115309
155413,R249,R179,01-00-00,86 ST,456,05/23/2017,00:00:00,REGULAR,2119747,33116024
155414,R249,R179,01-00-00,86 ST,456,05/23/2017,04:00:00,REGULAR,2119769,33116074
155415,R249,R179,01-00-00,86 ST,456,05/23/2017,08:00:00,REGULAR,2119832,33116963
155416,R249,R179,01-00-00,86 ST,456,05/23/2017,12:00:00,REGULAR,2119899,33118832
155417,R249,R179,01-00-00,86 ST,456,05/23/2017,16:00:00,REGULAR,2120088,33120406
155418,R249,R179,01-00-00,86 ST,456,05/23/2017,20:00:00,REGULAR,2120450,33123112
155419,R249,R179,01-00-00,86 ST,456,05/24/2017,00:00:00,REGULAR,2120545,33123990
155420,R249,R179,01-00-00,86 ST,456,05/24/2017,04:00:00,REGULAR,2120561,33124060
155421,R249,R179,01-00-00,86 ST,456,05/24/2017,08:00:00,REGULAR,2120643,33124865
155422,R249,R179,01-00-00,86 ST,456,05/24/2017,12:00:00,REGULAR,2120719,33126766
155423,R249,R179,01-00-00,86 ST,456,05/24/2017,16:00:00,REGULAR,2120891,33128454
155424,R249,R179,01-00-00,86 ST,456,05/24/2017,20:00:00,REGULAR,2121243,33131134
...,...,...,...,...,...,...,...,...,...,...
156289,R250,R179,00-00-0B,86 ST,456,05/22/2017,00:00:00,REGULAR,27780332,14617683
156290,R250,R179,00-00-0B,86 ST,456,05/22/2017,04:00:00,REGULAR,27780350,14617712
156291,R250,R179,00-00-0B,86 ST,456,05/22/2017,08:00:00,REGULAR,27780703,14618022
156292,R250,R179,00-00-0B,86 ST,456,05/22/2017,12:00:00,REGULAR,27781759,14618336
156293,R250,R179,00-00-0B,86 ST,456,05/22/2017,16:00:00,REGULAR,27782606,14618640
156294,R250,R179,00-00-0B,86 ST,456,05/22/2017,20:00:00,REGULAR,27783892,14618930
156295,R250,R179,00-00-0B,86 ST,456,05/23/2017,00:00:00,REGULAR,27784225,14619243
156296,R250,R179,00-00-0B,86 ST,456,05/23/2017,04:00:00,REGULAR,27784241,14619273
156297,R250,R179,00-00-0B,86 ST,456,05/23/2017,08:00:00,REGULAR,27784635,14619567
156298,R250,R179,00-00-0B,86 ST,456,05/23/2017,12:00:00,REGULAR,27785836,14619830
156299,R250,R179,00-00-0B,86 ST,456,05/23/2017,16:00:00,REGULAR,27786506,14620157
156300,R250,R179,00-00-0B,86 ST,456,05/23/2017,20:00:00,REGULAR,27787245,14620467
156301,R250,R179,00-00-0B,86 ST,456,05/24/2017,00:00:00,REGULAR,27787533,14620780
156302,R250,R179,00-00-0B,86 ST,456,05/24/2017,04:00:00,REGULAR,27787550,14620810
156303,R250,R179,00-00-0B,86 ST,456,05/24/2017,08:00:00,REGULAR,27787826,14621083
156304,R250,R179,00-00-0B,86 ST,456,05/24/2017,12:00:00,REGULAR,27789003,14621404
156305,R250,R179,00-00-0B,86 ST,456,05/24/2017,16:00:00,REGULAR,27789927,14621698
156306,R250,R179,00-00-0B,86 ST,456,05/24/2017,20:00:00,REGULAR,27791305,14622007
156307,R250,R179,00-00-0B,86 ST,456,05/25/2017,00:00:00,REGULAR,27791678,14622380
156308,R250,R179,00-00-0B,86 ST,456,05/25/2017,04:00:00,REGULAR,27791700,14622413
156309,R250,R179,00-00-0B,86 ST,456,05/25/2017,08:00:00,REGULAR,27792003,14622678
156310,R250,R179,00-00-0B,86 ST,456,05/25/2017,12:00:00,REGULAR,27793030,14622977
156311,R250,R179,00-00-0B,86 ST,456,05/25/2017,16:00:00,REGULAR,27794001,14623336
156312,R250,R179,00-00-0B,86 ST,456,05/25/2017,20:00:00,REGULAR,27795270,14623604
156313,R250,R179,00-00-0B,86 ST,456,05/26/2017,00:00:00,REGULAR,27795574,14623780
156314,R250,R179,00-00-0B,86 ST,456,05/26/2017,04:00:00,REGULAR,27795603,14623814
156315,R250,R179,00-00-0B,86 ST,456,05/26/2017,08:00:00,REGULAR,27795866,14624108
156316,R250,R179,00-00-0B,86 ST,456,05/26/2017,12:00:00,REGULAR,27796702,14624440
156317,R250,R179,00-00-0B,86 ST,456,05/26/2017,16:00:00,REGULAR,27797746,14624750
156318,R250,R179,00-00-0B,86 ST,456,05/26/2017,20:00:00,REGULAR,27798857,14625085